### ISSUE TITLE
could not access _viewportElement, can't attach scroll handler.

### ISSUE THREAD

**Issue by aminomancer** [simonhaenisch/hyper-fading-scrollbar#1]
Brand new install of hyper. this is the only plugin. also it seems like hyper's scrollbar is really messed up in general now. it's clipped on both sides and has a completely inconsistent horizontal positioning/margin/padding. like switching between two empty tabs shows the scrollbar's position is basically arbitrary. it's too large for whatever container is clipping it. I can't fix it with custom css because the whole thing is implemented in javascript in that asar file and I think that's mostly beyond my knowledge.

**Comment by simonhaenisch** [comment]
By brand new install, do you mean version 3.0.2? Which platform are you on?

**Comment by aminomancer** [comment]
Sorry—by brand new install I just meant no other extensions or modifications made. Yes, 3.0.2. Windows version 1903. On the about page it says Renderer: WebGL, if that's important. I thought this might be due to some kind of DWM scaling issue, because I'm using a 2560x1440 monitor with 125% scaling. But if I override the scaling using that method of changing the executable's properties it doesn't help. Application looks exactly the same, but system and system (enhanced) make all the text super pixellated and blurry. And aside from that I don't know any ways to tinker with window scaling. After posting this, I tried installing the extension in hyper 2.1.2 but it was still the same. The scrollbar was cut off and had a random horizontal position both before and after installing the extension. The amount it's cut off by and the side (left or right) that gets cut off seems to depend on the custom padding value, but it's always at least 1 pixel. I tested a lot of values and couldn't find any that weren't cut off at all. The extension does affect it, like values that only get cut off by 1 pixel without the extension usually get cut off by more. And values that only get cut off by 1 pixel with the extension get cut off by more without it. Or the extension makes it cut off on the other side instead. So it seems to have some interaction with this bug but after more testing, I don't think the extension could be seen as a causal factor. But maybe you know a bit about how the scrollbars are implemented and could still help me. I tried digging through the browser toolbox but it seems like the scrollbar's container is constantly changed by javascript events so I can't seem to fix the issue by inputting custom CSS in the settings file. It'll just be overwritten instantly, I think.

An example of a value that gets cut off the least with the extension installed is padding: '12px 4px 12px 14px' but the right side is still cut off by a pixel. But at least its horizontal position seems to stay constant, it wiggles left and right by a pixel or so if I change the window size, but at the default window size it stays constant no matter how many times I open hyper. So that sort of works but the cut off is irritating enough that I just make the scrollbar completely invisible in practice lol.

**Comment by simonhaenisch** [comment]
Don't really understand your issue but this is the code that throws the error:

https://github.com/simonhaenisch/hyper-fading-scrollbar/blob/eb42a4df2e2f0176478f4cc909255781611a9814/index.js#L73-L78

I actually get that warning, too, probably because the xterm internals have changed.

`_viewportElement` is an internal implementation detail of xterm and not a documented API, which must have changed... however, all that happens in this case is that the scroll event handler is not attached, meaning the fading effect won't work when scrolling, only on hover (which is exactly what I'm experiencing).

Sorry, can't help you with your clipped scrollbar issues.

**Comment by simonhaenisch** [comment]
Fixed the plugin to work with Hyper v3 in ff644235b937c949ca4792e01250b377dceef3b0.
